[package]
name = "spritely"
version = "0.1.0"
edition = "2021"
description = "Sprite-related utils for the Image crate."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/spritely"

[dependencies]
image = "0.24"